schema {
  query: Query
  mutation: Mutation
}

"""A high precision floating point value represented as a string"""
scalar BigFloat

"""
Boolean expression comparing fields on type "BigFloat"
"""
input BigFloatFilter {
  eq: BigFloat
  gt: BigFloat
  gte: BigFloat
  in: [BigFloat!]
  is: FilterIs
  lt: BigFloat
  lte: BigFloat
  neq: BigFloat
}

"""
Boolean expression comparing fields on type "BigFloatList"
"""
input BigFloatListFilter {
  containedBy: [BigFloat!]
  contains: [BigFloat!]
  eq: [BigFloat!]
  is: FilterIs
  overlaps: [BigFloat!]
}

"""An arbitrary size integer represented as a string"""
scalar BigInt

"""
Boolean expression comparing fields on type "BigInt"
"""
input BigIntFilter {
  eq: BigInt
  gt: BigInt
  gte: BigInt
  in: [BigInt!]
  is: FilterIs
  lt: BigInt
  lte: BigInt
  neq: BigInt
}

"""
Boolean expression comparing fields on type "BigIntList"
"""
input BigIntListFilter {
  containedBy: [BigInt!]
  contains: [BigInt!]
  eq: [BigInt!]
  is: FilterIs
  overlaps: [BigInt!]
}

"""
Boolean expression comparing fields on type "Boolean"
"""
input BooleanFilter {
  eq: Boolean
  is: FilterIs
}

"""
Boolean expression comparing fields on type "BooleanList"
"""
input BooleanListFilter {
  containedBy: [Boolean!]
  contains: [Boolean!]
  eq: [Boolean!]
  is: FilterIs
  overlaps: [Boolean!]
}

"""
An opaque string using for tracking a position in results during pagination
"""
scalar Cursor

"""A date without time information"""
scalar Date

"""
Boolean expression comparing fields on type "Date"
"""
input DateFilter {
  eq: Date
  gt: Date
  gte: Date
  in: [Date!]
  is: FilterIs
  lt: Date
  lte: Date
  neq: Date
}

"""
Boolean expression comparing fields on type "DateList"
"""
input DateListFilter {
  containedBy: [Date!]
  contains: [Date!]
  eq: [Date!]
  is: FilterIs
  overlaps: [Date!]
}

"""A date and time"""
scalar Datetime

"""
Boolean expression comparing fields on type "Datetime"
"""
input DatetimeFilter {
  eq: Datetime
  gt: Datetime
  gte: Datetime
  in: [Datetime!]
  is: FilterIs
  lt: Datetime
  lte: Datetime
  neq: Datetime
}

"""
Boolean expression comparing fields on type "DatetimeList"
"""
input DatetimeListFilter {
  containedBy: [Datetime!]
  contains: [Datetime!]
  eq: [Datetime!]
  is: FilterIs
  overlaps: [Datetime!]
}

enum FilterIs {
  NOT_NULL
  NULL
}

"""
Boolean expression comparing fields on type "Float"
"""
input FloatFilter {
  eq: Float
  gt: Float
  gte: Float
  in: [Float!]
  is: FilterIs
  lt: Float
  lte: Float
  neq: Float
}

"""
Boolean expression comparing fields on type "FloatList"
"""
input FloatListFilter {
  containedBy: [Float!]
  contains: [Float!]
  eq: [Float!]
  is: FilterIs
  overlaps: [Float!]
}

"""
Boolean expression comparing fields on type "ID"
"""
input IDFilter {
  eq: ID
}

"""
Boolean expression comparing fields on type "Int"
"""
input IntFilter {
  eq: Int
  gt: Int
  gte: Int
  in: [Int!]
  is: FilterIs
  lt: Int
  lte: Int
  neq: Int
}

"""
Boolean expression comparing fields on type "IntList"
"""
input IntListFilter {
  containedBy: [Int!]
  contains: [Int!]
  eq: [Int!]
  is: FilterIs
  overlaps: [Int!]
}

"""A Javascript Object Notation value serialized as a string"""
scalar JSON

"""The root type for creating and mutating data"""
type Mutation {
  """Deletes zero or more records from the `app_settings` collection"""
  deleteFromapp_settingsCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1
    """Restricts the mutation's impact to records matching the criteria"""
    filter: app_settingsFilter
  ): app_settingsDeleteResponse!
  """Deletes zero or more records from the `guest` collection"""
  deleteFromguestCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1
    """Restricts the mutation's impact to records matching the criteria"""
    filter: guestFilter
  ): guestDeleteResponse!
  """Deletes zero or more records from the `invite` collection"""
  deleteFrominviteCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1
    """Restricts the mutation's impact to records matching the criteria"""
    filter: inviteFilter
  ): inviteDeleteResponse!
  """Deletes zero or more records from the `rsvp` collection"""
  deleteFromrsvpCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1
    """Restricts the mutation's impact to records matching the criteria"""
    filter: rsvpFilter
  ): rsvpDeleteResponse!
  """Deletes zero or more records from the `seat_assignment` collection"""
  deleteFromseat_assignmentCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1
    """Restricts the mutation's impact to records matching the criteria"""
    filter: seat_assignmentFilter
  ): seat_assignmentDeleteResponse!
  """Deletes zero or more records from the `seating_element` collection"""
  deleteFromseating_elementCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1
    """Restricts the mutation's impact to records matching the criteria"""
    filter: seating_elementFilter
  ): seating_elementDeleteResponse!
  """Adds one or more `app_settings` records to the collection"""
  insertIntoapp_settingsCollection(objects: [app_settingsInsertInput!]!): app_settingsInsertResponse
  """Adds one or more `guest` records to the collection"""
  insertIntoguestCollection(objects: [guestInsertInput!]!): guestInsertResponse
  """Adds one or more `invite` records to the collection"""
  insertIntoinviteCollection(objects: [inviteInsertInput!]!): inviteInsertResponse
  """Adds one or more `rsvp` records to the collection"""
  insertIntorsvpCollection(objects: [rsvpInsertInput!]!): rsvpInsertResponse
  """Adds one or more `seat_assignment` records to the collection"""
  insertIntoseat_assignmentCollection(objects: [seat_assignmentInsertInput!]!): seat_assignmentInsertResponse
  """Adds one or more `seating_element` records to the collection"""
  insertIntoseating_elementCollection(objects: [seating_elementInsertInput!]!): seating_elementInsertResponse
  track_envelope_open(p_invite_id: UUID!): Opaque
  track_invite_open(p_invite_id: UUID!): Opaque
  """Updates zero or more records in the `app_settings` collection"""
  updateapp_settingsCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1
    """Restricts the mutation's impact to records matching the criteria"""
    filter: app_settingsFilter
    """
    Fields that are set will be updated for all records matching the `filter`
    """
    set: app_settingsUpdateInput!
  ): app_settingsUpdateResponse!
  """Updates zero or more records in the `guest` collection"""
  updateguestCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1
    """Restricts the mutation's impact to records matching the criteria"""
    filter: guestFilter
    """
    Fields that are set will be updated for all records matching the `filter`
    """
    set: guestUpdateInput!
  ): guestUpdateResponse!
  """Updates zero or more records in the `invite` collection"""
  updateinviteCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1
    """Restricts the mutation's impact to records matching the criteria"""
    filter: inviteFilter
    """
    Fields that are set will be updated for all records matching the `filter`
    """
    set: inviteUpdateInput!
  ): inviteUpdateResponse!
  """Updates zero or more records in the `rsvp` collection"""
  updatersvpCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1
    """Restricts the mutation's impact to records matching the criteria"""
    filter: rsvpFilter
    """
    Fields that are set will be updated for all records matching the `filter`
    """
    set: rsvpUpdateInput!
  ): rsvpUpdateResponse!
  """Updates zero or more records in the `seat_assignment` collection"""
  updateseat_assignmentCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1
    """Restricts the mutation's impact to records matching the criteria"""
    filter: seat_assignmentFilter
    """
    Fields that are set will be updated for all records matching the `filter`
    """
    set: seat_assignmentUpdateInput!
  ): seat_assignmentUpdateResponse!
  """Updates zero or more records in the `seating_element` collection"""
  updateseating_elementCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1
    """Restricts the mutation's impact to records matching the criteria"""
    filter: seating_elementFilter
    """
    Fields that are set will be updated for all records matching the `filter`
    """
    set: seating_elementUpdateInput!
  ): seating_elementUpdateResponse!
}

interface Node {
  """Retrieves a record by `ID`"""
  nodeId: ID!
}

"""Any type not handled by the type system"""
scalar Opaque

"""
Boolean expression comparing fields on type "Opaque"
"""
input OpaqueFilter {
  eq: Opaque
  is: FilterIs
}

"""Defines a per-field sorting order"""
enum OrderByDirection {
  """Ascending order, nulls first"""
  AscNullsFirst
  """Ascending order, nulls last"""
  AscNullsLast
  """Descending order, nulls first"""
  DescNullsFirst
  """Descending order, nulls last"""
  DescNullsLast
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
}

"""The root type for querying data"""
type Query {
  """A pagable collection of type `app_settings`"""
  app_settingsCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor
    """Query values in the collection before the provided cursor"""
    before: Cursor
    """Filters to apply to the results set when querying from the collection"""
    filter: app_settingsFilter
    """Query the first `n` records in the collection"""
    first: Int
    """Query the last `n` records in the collection"""
    last: Int
    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int
    """Sort order to apply to the collection"""
    orderBy: [app_settingsOrderBy!]
  ): app_settingsConnection
  """A pagable collection of type `guest`"""
  guestCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor
    """Query values in the collection before the provided cursor"""
    before: Cursor
    """Filters to apply to the results set when querying from the collection"""
    filter: guestFilter
    """Query the first `n` records in the collection"""
    first: Int
    """Query the last `n` records in the collection"""
    last: Int
    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int
    """Sort order to apply to the collection"""
    orderBy: [guestOrderBy!]
  ): guestConnection
  """A pagable collection of type `invite`"""
  inviteCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor
    """Query values in the collection before the provided cursor"""
    before: Cursor
    """Filters to apply to the results set when querying from the collection"""
    filter: inviteFilter
    """Query the first `n` records in the collection"""
    first: Int
    """Query the last `n` records in the collection"""
    last: Int
    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int
    """Sort order to apply to the collection"""
    orderBy: [inviteOrderBy!]
  ): inviteConnection
  """Retrieve a record by its `ID`"""
  node(
    """The record's `ID`"""
    nodeId: ID!
  ): Node
  """A pagable collection of type `rsvp`"""
  rsvpCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor
    """Query values in the collection before the provided cursor"""
    before: Cursor
    """Filters to apply to the results set when querying from the collection"""
    filter: rsvpFilter
    """Query the first `n` records in the collection"""
    first: Int
    """Query the last `n` records in the collection"""
    last: Int
    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int
    """Sort order to apply to the collection"""
    orderBy: [rsvpOrderBy!]
  ): rsvpConnection
  """A pagable collection of type `seat_assignment`"""
  seat_assignmentCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor
    """Query values in the collection before the provided cursor"""
    before: Cursor
    """Filters to apply to the results set when querying from the collection"""
    filter: seat_assignmentFilter
    """Query the first `n` records in the collection"""
    first: Int
    """Query the last `n` records in the collection"""
    last: Int
    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int
    """Sort order to apply to the collection"""
    orderBy: [seat_assignmentOrderBy!]
  ): seat_assignmentConnection
  """A pagable collection of type `seating_element`"""
  seating_elementCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor
    """Query values in the collection before the provided cursor"""
    before: Cursor
    """Filters to apply to the results set when querying from the collection"""
    filter: seating_elementFilter
    """Query the first `n` records in the collection"""
    first: Int
    """Query the last `n` records in the collection"""
    last: Int
    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int
    """Sort order to apply to the collection"""
    orderBy: [seating_elementOrderBy!]
  ): seating_elementConnection
}

"""
Boolean expression comparing fields on type "String"
"""
input StringFilter {
  eq: String
  gt: String
  gte: String
  ilike: String
  in: [String!]
  iregex: String
  is: FilterIs
  like: String
  lt: String
  lte: String
  neq: String
  regex: String
  startsWith: String
}

"""
Boolean expression comparing fields on type "StringList"
"""
input StringListFilter {
  containedBy: [String!]
  contains: [String!]
  eq: [String!]
  is: FilterIs
  overlaps: [String!]
}

"""A time without date information"""
scalar Time

"""
Boolean expression comparing fields on type "Time"
"""
input TimeFilter {
  eq: Time
  gt: Time
  gte: Time
  in: [Time!]
  is: FilterIs
  lt: Time
  lte: Time
  neq: Time
}

"""
Boolean expression comparing fields on type "TimeList"
"""
input TimeListFilter {
  containedBy: [Time!]
  contains: [Time!]
  eq: [Time!]
  is: FilterIs
  overlaps: [Time!]
}

"""A universally unique identifier"""
scalar UUID

"""
Boolean expression comparing fields on type "UUID"
"""
input UUIDFilter {
  eq: UUID
  in: [UUID!]
  is: FilterIs
  neq: UUID
}

"""
Boolean expression comparing fields on type "UUIDList"
"""
input UUIDListFilter {
  containedBy: [UUID!]
  contains: [UUID!]
  eq: [UUID!]
  is: FilterIs
  overlaps: [UUID!]
}

type app_settings implements Node {
  key: String!
  """Globally Unique Record Identifier"""
  nodeId: ID!
  updated_at: Datetime!
  value: String!
}

type app_settingsConnection {
  edges: [app_settingsEdge!]!
  pageInfo: PageInfo!
}

type app_settingsDeleteResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [app_settings!]!
}

type app_settingsEdge {
  cursor: String!
  node: app_settings!
}

input app_settingsFilter {
  """
  Returns true only if all its inner filters are true, otherwise returns false
  """
  and: [app_settingsFilter!]
  key: StringFilter
  nodeId: IDFilter
  """Negates a filter"""
  not: app_settingsFilter
  """
  Returns true if at least one of its inner filters is true, otherwise returns false
  """
  or: [app_settingsFilter!]
  updated_at: DatetimeFilter
  value: StringFilter
}

input app_settingsInsertInput {
  key: String
  updated_at: Datetime
  value: String
}

type app_settingsInsertResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [app_settings!]!
}

input app_settingsOrderBy {
  key: OrderByDirection
  updated_at: OrderByDirection
  value: OrderByDirection
}

input app_settingsUpdateInput {
  key: String
  updated_at: Datetime
  value: String
}

type app_settingsUpdateResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [app_settings!]!
}

type guest implements Node {
  created_at: Datetime!
  full_name: String!
  id: UUID!
  invite: invite
  invite_id: UUID
  """Globally Unique Record Identifier"""
  nodeId: ID!
  seat_assignment: seat_assignment
}

type guestConnection {
  edges: [guestEdge!]!
  pageInfo: PageInfo!
}

type guestDeleteResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [guest!]!
}

type guestEdge {
  cursor: String!
  node: guest!
}

input guestFilter {
  """
  Returns true only if all its inner filters are true, otherwise returns false
  """
  and: [guestFilter!]
  created_at: DatetimeFilter
  full_name: StringFilter
  id: UUIDFilter
  invite_id: UUIDFilter
  nodeId: IDFilter
  """Negates a filter"""
  not: guestFilter
  """
  Returns true if at least one of its inner filters is true, otherwise returns false
  """
  or: [guestFilter!]
}

input guestInsertInput {
  created_at: Datetime
  full_name: String
  id: UUID
  invite_id: UUID
}

type guestInsertResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [guest!]!
}

input guestOrderBy {
  created_at: OrderByDirection
  full_name: OrderByDirection
  id: OrderByDirection
  invite_id: OrderByDirection
}

input guestUpdateInput {
  created_at: Datetime
  full_name: String
  id: UUID
  invite_id: UUID
}

type guestUpdateResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [guest!]!
}

type invite implements Node {
  created_at: Datetime!
  envelope_opened_at: Datetime
  first_opened_at: Datetime
  guestCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor
    """Query values in the collection before the provided cursor"""
    before: Cursor
    """Filters to apply to the results set when querying from the collection"""
    filter: guestFilter
    """Query the first `n` records in the collection"""
    first: Int
    """Query the last `n` records in the collection"""
    last: Int
    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int
    """Sort order to apply to the collection"""
    orderBy: [guestOrderBy!]
  ): guestConnection
  id: UUID!
  message: String
  name: String
  """Globally Unique Record Identifier"""
  nodeId: ID!
  number_of_attendees: Int!
  open_count: Int!
  rsvpCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor
    """Query values in the collection before the provided cursor"""
    before: Cursor
    """Filters to apply to the results set when querying from the collection"""
    filter: rsvpFilter
    """Query the first `n` records in the collection"""
    first: Int
    """Query the last `n` records in the collection"""
    last: Int
    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int
    """Sort order to apply to the collection"""
    orderBy: [rsvpOrderBy!]
  ): rsvpConnection
  sent: Boolean
}

type inviteConnection {
  edges: [inviteEdge!]!
  pageInfo: PageInfo!
}

type inviteDeleteResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [invite!]!
}

type inviteEdge {
  cursor: String!
  node: invite!
}

input inviteFilter {
  """
  Returns true only if all its inner filters are true, otherwise returns false
  """
  and: [inviteFilter!]
  created_at: DatetimeFilter
  envelope_opened_at: DatetimeFilter
  first_opened_at: DatetimeFilter
  id: UUIDFilter
  message: StringFilter
  name: StringFilter
  nodeId: IDFilter
  """Negates a filter"""
  not: inviteFilter
  number_of_attendees: IntFilter
  open_count: IntFilter
  """
  Returns true if at least one of its inner filters is true, otherwise returns false
  """
  or: [inviteFilter!]
  sent: BooleanFilter
}

input inviteInsertInput {
  created_at: Datetime
  envelope_opened_at: Datetime
  first_opened_at: Datetime
  id: UUID
  message: String
  name: String
  number_of_attendees: Int
  open_count: Int
  sent: Boolean
}

type inviteInsertResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [invite!]!
}

input inviteOrderBy {
  created_at: OrderByDirection
  envelope_opened_at: OrderByDirection
  first_opened_at: OrderByDirection
  id: OrderByDirection
  message: OrderByDirection
  name: OrderByDirection
  number_of_attendees: OrderByDirection
  open_count: OrderByDirection
  sent: OrderByDirection
}

input inviteUpdateInput {
  created_at: Datetime
  envelope_opened_at: Datetime
  first_opened_at: Datetime
  id: UUID
  message: String
  name: String
  number_of_attendees: Int
  open_count: Int
  sent: Boolean
}

type inviteUpdateResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [invite!]!
}

type rsvp implements Node {
  additional_notes: String
  attending: Boolean
  created_at: Datetime!
  dietary: String
  email: String
  id: UUID!
  invite: invite
  invite_id: UUID
  """Globally Unique Record Identifier"""
  nodeId: ID!
  physical_invite: Boolean
  song_recommendations: String
  transit: Boolean
}

type rsvpConnection {
  edges: [rsvpEdge!]!
  pageInfo: PageInfo!
}

type rsvpDeleteResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [rsvp!]!
}

type rsvpEdge {
  cursor: String!
  node: rsvp!
}

input rsvpFilter {
  additional_notes: StringFilter
  """
  Returns true only if all its inner filters are true, otherwise returns false
  """
  and: [rsvpFilter!]
  attending: BooleanFilter
  created_at: DatetimeFilter
  dietary: StringFilter
  email: StringFilter
  id: UUIDFilter
  invite_id: UUIDFilter
  nodeId: IDFilter
  """Negates a filter"""
  not: rsvpFilter
  """
  Returns true if at least one of its inner filters is true, otherwise returns false
  """
  or: [rsvpFilter!]
  physical_invite: BooleanFilter
  song_recommendations: StringFilter
  transit: BooleanFilter
}

input rsvpInsertInput {
  additional_notes: String
  attending: Boolean
  created_at: Datetime
  dietary: String
  email: String
  id: UUID
  invite_id: UUID
  physical_invite: Boolean
  song_recommendations: String
  transit: Boolean
}

type rsvpInsertResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [rsvp!]!
}

input rsvpOrderBy {
  additional_notes: OrderByDirection
  attending: OrderByDirection
  created_at: OrderByDirection
  dietary: OrderByDirection
  email: OrderByDirection
  id: OrderByDirection
  invite_id: OrderByDirection
  physical_invite: OrderByDirection
  song_recommendations: OrderByDirection
  transit: OrderByDirection
}

input rsvpUpdateInput {
  additional_notes: String
  attending: Boolean
  created_at: Datetime
  dietary: String
  email: String
  id: UUID
  invite_id: UUID
  physical_invite: Boolean
  song_recommendations: String
  transit: Boolean
}

type rsvpUpdateResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [rsvp!]!
}

type seat_assignment implements Node {
  created_at: Datetime!
  element_id: UUID!
  guest: guest
  guest_id: UUID!
  id: UUID!
  """Globally Unique Record Identifier"""
  nodeId: ID!
  seat_index: Int!
  seating_element: seating_element
}

type seat_assignmentConnection {
  edges: [seat_assignmentEdge!]!
  pageInfo: PageInfo!
}

type seat_assignmentDeleteResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [seat_assignment!]!
}

type seat_assignmentEdge {
  cursor: String!
  node: seat_assignment!
}

input seat_assignmentFilter {
  """
  Returns true only if all its inner filters are true, otherwise returns false
  """
  and: [seat_assignmentFilter!]
  created_at: DatetimeFilter
  element_id: UUIDFilter
  guest_id: UUIDFilter
  id: UUIDFilter
  nodeId: IDFilter
  """Negates a filter"""
  not: seat_assignmentFilter
  """
  Returns true if at least one of its inner filters is true, otherwise returns false
  """
  or: [seat_assignmentFilter!]
  seat_index: IntFilter
}

input seat_assignmentInsertInput {
  created_at: Datetime
  element_id: UUID
  guest_id: UUID
  id: UUID
  seat_index: Int
}

type seat_assignmentInsertResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [seat_assignment!]!
}

input seat_assignmentOrderBy {
  created_at: OrderByDirection
  element_id: OrderByDirection
  guest_id: OrderByDirection
  id: OrderByDirection
  seat_index: OrderByDirection
}

input seat_assignmentUpdateInput {
  created_at: Datetime
  element_id: UUID
  guest_id: UUID
  id: UUID
  seat_index: Int
}

type seat_assignmentUpdateResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [seat_assignment!]!
}

type seating_element implements Node {
  created_at: Datetime!
  height: Float!
  id: UUID!
  kind: String!
  label: String
  """Globally Unique Record Identifier"""
  nodeId: ID!
  rotation: Float!
  seat_assignmentCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor
    """Query values in the collection before the provided cursor"""
    before: Cursor
    """Filters to apply to the results set when querying from the collection"""
    filter: seat_assignmentFilter
    """Query the first `n` records in the collection"""
    first: Int
    """Query the last `n` records in the collection"""
    last: Int
    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int
    """Sort order to apply to the collection"""
    orderBy: [seat_assignmentOrderBy!]
  ): seat_assignmentConnection
  seat_offsets: [Float]
  seats_bottom: Int!
  seats_left: Int!
  seats_right: Int!
  seats_top: Int!
  width: Float!
  x: Float!
  y: Float!
}

type seating_elementConnection {
  edges: [seating_elementEdge!]!
  pageInfo: PageInfo!
}

type seating_elementDeleteResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [seating_element!]!
}

type seating_elementEdge {
  cursor: String!
  node: seating_element!
}

input seating_elementFilter {
  """
  Returns true only if all its inner filters are true, otherwise returns false
  """
  and: [seating_elementFilter!]
  created_at: DatetimeFilter
  height: FloatFilter
  id: UUIDFilter
  kind: StringFilter
  label: StringFilter
  nodeId: IDFilter
  """Negates a filter"""
  not: seating_elementFilter
  """
  Returns true if at least one of its inner filters is true, otherwise returns false
  """
  or: [seating_elementFilter!]
  rotation: FloatFilter
  seat_offsets: FloatListFilter
  seats_bottom: IntFilter
  seats_left: IntFilter
  seats_right: IntFilter
  seats_top: IntFilter
  width: FloatFilter
  x: FloatFilter
  y: FloatFilter
}

input seating_elementInsertInput {
  created_at: Datetime
  height: Float
  id: UUID
  kind: String
  label: String
  rotation: Float
  seat_offsets: [Float]
  seats_bottom: Int
  seats_left: Int
  seats_right: Int
  seats_top: Int
  width: Float
  x: Float
  y: Float
}

type seating_elementInsertResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [seating_element!]!
}

input seating_elementOrderBy {
  created_at: OrderByDirection
  height: OrderByDirection
  id: OrderByDirection
  kind: OrderByDirection
  label: OrderByDirection
  rotation: OrderByDirection
  seats_bottom: OrderByDirection
  seats_left: OrderByDirection
  seats_right: OrderByDirection
  seats_top: OrderByDirection
  width: OrderByDirection
  x: OrderByDirection
  y: OrderByDirection
}

input seating_elementUpdateInput {
  created_at: Datetime
  height: Float
  id: UUID
  kind: String
  label: String
  rotation: Float
  seat_offsets: [Float]
  seats_bottom: Int
  seats_left: Int
  seats_right: Int
  seats_top: Int
  width: Float
  x: Float
  y: Float
}

type seating_elementUpdateResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!
  """Array of records impacted by the mutation"""
  records: [seating_element!]!
}